### ISSUE TITLE
Final score multiplication

### ISSUE THREAD

**Issue by hguan6** [nreimers/beir-sparta#1]
https://github.com/nreimers/beir-sparta/blob/4b686e006f416b4e58e45cf45b9c51b1f1b28d27/train_sparta_msmarco.py#L351

Why's the final score multiplied by 10?

**Comment by nreimers** [comment]
CrossEntropyLoss often does not work well when  the scores are small and the difference are small between relevant and irrelevant passages. The 10 increases the differences, leading to a better model

**Comment by hguan6** [comment]
Thank you!
